### PR TITLE
add support for API keys

### PR DESCRIPTION
**Pull request by alexguzun**
As you might know, the API now requires a key, that can be obtained by becoming a suporter. Current version of library does not work anymore ( Issue #11 ).

Unit tests are getting the key from environment:
`var apiKey = os.Getenv("OMDB_API_KEY")`

This also means that one will have to  [configure the environment variable in TravisCI](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings).

### CODE REVIEW

**Comment by eefret** [comment]
Thanks for adding this, could you check the unit tests, probably failing because of an unsupported API_KEY? can you confirm? if you can't I'll merge in the weekend

**Comment by alexguzun** [comment]
Hi @eefret! Any updates on this PR?

**Comment by eefret** [comment]
Yeah sure I downloaded the build and the tests work correctly

**Comment by eefret** [comment]
thanks @alexguzun

**Comment by alexguzun** [comment]
Thanks for merging the PR! 
Don't forget to [configure the environment variable in TravisCI.](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings)

**Pull request merged**
