### PR TITLE
Code cleanup and new features

### PR DESCRIPTION
**Pull request by agnivade**
Hi there,

Thank you for the good work in writing the library. I forked it and added a little bit of polish. Below is a list of items covered in the PR-

- Now passing a struct in the API functions. This makes the API more scalable if more fields are to come in the future. And you don't have to pass "" if you don't want to search by a certain field.
- Added search by `type`. #4 
- Added much more unit tests. And added fail scenario too.

### CODE REVIEW

**Comment by codnee** [comment]
Please update the README to point to the original repo.

@efreet: thoughts?

**Comment by agnivade** [comment]
Ahh crap, problems of sending PR from the master branch. When I made the PR, the README was indeed pointing to the original repo. Then I made the changes to point to my repo, which got reflected in the PR as well. 

Fixed it now.

**Comment by agnivade** [comment]
@eefret  - Oops. Fixed it.

**Comment by eefret** [comment]
I agree with the changes thanks for the PR, merging

**Pull request merged**
